Task1 Orders Table
vlaaaaaad/creamy-tasks pull request #1
Opened 2024-10-08 15:32 UTC by vlaaaaaad

2024-10-08 15:58 UTC, OlgaLyakhvatska requested changes

2024-10-08 15:58 UTC, OlgaLyakhvatska commented on src/App.js
> +  const [products, setProducts] = useState(
пожалуйста, используй стрелочную функцию

2024-10-08 15:58 UTC, OlgaLyakhvatska commented on src/App.js
> +    const reducedProducts = products.reduce((accumulator, currentValue) => {
ты можешь сразу подготовить данные для таблицы useEffect - здесь лишний

2024-10-08 15:58 UTC, OlgaLyakhvatska commented on src/App.js
> +                  (product.status.value === "Available" && available) ||
- надежнее сравнивать статусы по id, а не по тексту
- так же у тебя есть `setProducts` с которым ты можешь работать и делать при `onChange` фильтрацию, а таблица пускай работает только с `products.map(....`

2024-10-08 15:58 UTC, OlgaLyakhvatska commented on src/App.js
> +          <button
на видео, когда ты нажимаешь кнопку сброса фильтров у тебя таблица пустая, а должно быть все данные без фильтров

2024-10-21 18:16 UTC, OlgaLyakhvatska requested changes

2024-10-21 18:16 UTC, OlgaLyakhvatska commented on src/products/components/ProductTable.js
> +export const ProductTable = () => {
- не увидела папку сontainers, в которой можно перенести логику  initialProducts и передать их в компонент 
- не увидела, чтобы у продуктов были свои роуты
- не увидела Ramda

2024-10-27 19:48 UTC, OlgaLyakhvatskaya requested changes

2024-10-27 19:48 UTC, OlgaLyakhvatskaya commented on src/products/routes.js
> +const AppRoutes = () => {
`ProductsRoutes` - названия переменных/функций должно всегда подсказывать след. разработчику что и как происходит. в данном случае `AppRoutes` - говорит об роутах всего приложения, но не конкретного роута продуктов. Пожалуйста, обращай всегда внимание на наименования.

2024-10-27 19:48 UTC, OlgaLyakhvatskaya commented on src/products/routes.js
> +    <BrowserRouter>
`BrowserRouter ` - верни в `App.js`. У тебя должен быть главный роут в который ты встраиваешь дочерние.

2024-10-27 19:54 UTC, OlgaLyakhvatskaya requested changes

2024-10-27 19:54 UTC, OlgaLyakhvatskaya commented on src/products/containers/ProductsContainer.js
>    //     initialProducts.filter((product) => product.status.id === statusId)
Пожалуйста, следи чтобы перед пушем не было закомментированого кода

2024-10-27 19:54 UTC, OlgaLyakhvatskaya commented on src/products/containers/ProductsContainer.js
>  import { ProductTable } from "../components/ProductTable.js";
У нас на проекте предпочтительно использовать абсолютный путь, а не относительный - это просто из рубрики - "Наш проект" :) :) :)

2024-10-28 10:05 UTC, merged